DEFAULT_MODEL_NAME = "gemini-2.5-flash"
DEFAULT_REASONING_EFFORT = "low"
MODEL_FARM_PROVIDER = "Model Farm"
OLLAMA_PROVIDER = "Ollama"

MODEL_FARM_MODEL_OPTIONS = [
	"gemini-2.5-flash",
	"gpt-5-nano-2025-08-07",
]
# Add any locally available Ollama model tags here. These are shown in the UI dropdown.
OLLAMA_MODEL_OPTIONS = [
    "llama3.1:8b",
]
DEFAULT_OLLAMA_MODEL = "llama3.1:8b"

EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
EMBEDDING_DEVICE = "cpu"
EMBEDDING_DIMENSION = 1024
DOCUMENTS_DIR = "documents"
CHROMA_DB_DIR = "chroma_db"
CHROMA_COLLECTION_NAME = "knowledge_chunks"
RESET_COLLECTION_WHEN_EMPTY = True
LOGS_DIR = "logs"

KNOWLEDGE_CHUNK_SIZE = 900
KNOWLEDGE_CHUNK_OVERLAP = 180

HYBRID_ALPHA = 0.65
VECTOR_TOP_K = 12
SPARSE_TOP_K = 12
FINAL_TOP_K = 5
MIN_DENSE_RELEVANCE_SCORE = 0.25
