import streamlit as st

from src.chatbot.services.chat_service import ChatService


def render_simple_chat_tab(chat_service: ChatService, provider: str, model: str) -> None:
    st.subheader("Simple Chat")
    st.caption("Ask anything. The answer is generated by your LLM API configured in .env.")

    if "simple_chat_history" not in st.session_state:
        st.session_state.simple_chat_history = []

    if st.button("Clear Chat"):
        st.session_state.simple_chat_history = []
        st.rerun()

    for message in st.session_state.simple_chat_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    prompt = st.chat_input("Type your message for Simple Chat")
    if not prompt:
        return

    st.session_state.simple_chat_history.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                answer = chat_service.simple_chat(
                    st.session_state.simple_chat_history,
                    provider=provider,
                    model=model,
                )
            except Exception as ex:
                answer = f"Error: {ex}"
        st.markdown(answer)

    st.session_state.simple_chat_history.append({"role": "assistant", "content": answer})
